# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'eShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for DDBB
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

# QA and CI
pod 'SwiftLint', '~> 0.16.1'
pod 'R.swift', '~> 3.3.0'
 

  target 'eShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
