INSERT INTO SHOPS VALUES (null, 'M');
INSERT INTO SHOPS VALUES (null, 'B');

INSERT INTO PRODUCTS VALUES (null, 'C');
INSERT INTO PRODUCTS VALUES (null, 'F');
INSERT INTO PRODUCTS VALUES (null, 'A');


INSERT INTO PRICES VALUES (1, 1,10);
INSERT INTO PRICES VALUES (2, 2,20);
INSERT INTO PRICES VALUES (1, 1,15);
INSERT INTO PRICES VALUES (1, 2,13);
