INSERT INTO SHOPS VALUES (null, 'Mercadona','S. Andreu B.');
INSERT INTO SHOPS VALUES (null, 'Bon Preu','Pallejà');
INSERT INTO SHOPS VALUES (null, 'Condis', 'Pallejà');
INSERT INTO SHOPS VALUES (null, 'Area de Guisona', 'Pallejà');

INSERT INTO PRODUCTS VALUES (null, 'Atún pack 3');
INSERT INTO PRODUCTS VALUES (null, 'Pavo lonchas');
INSERT INTO PRODUCTS VALUES (null, 'Pavo rollo');
INSERT INTO PRODUCTS VALUES (null, 'Tostadas');
INSERT INTO PRODUCTS VALUES (null, 'Leche');


INSERT INTO PRICES VALUES (1, 1,10,3);
INSERT INTO PRICES VALUES (4, 1,15,3);
INSERT INTO PRICES VALUES (2, 2,10,3);
INSERT INTO PRICES VALUES (4, 2,10,3);
INSERT INTO PRICES VALUES (1, 3,20,3);
INSERT INTO PRICES VALUES (4, 3,10,3);
INSERT INTO PRICES VALUES (2, 4,10,3);
INSERT INTO PRICES VALUES (4, 4,15,3);
INSERT INTO PRICES VALUES (1, 5,10,3);
INSERT INTO PRICES VALUES (4, 5,10,3);



